blogplot_theme = theme(legend.background = element_rect(fill = "#1D1E28",
                                                      color = "#1D1E28"),
                     legend.title = element_blank(),
                     legend.box.background = element_rect(fill = "#1D1E28",
                                                          color = "#1D1E28"),
                     panel.background = element_rect(fill = "#1D1E28",
                                                     color = "#1D1E28"),
                     panel.grid.major = element_line(color = "#9C9C9C"),
                     plot.background = element_rect(fill = "#1D1E28",
                                                    color = "#1D1E28"),
                     axis.ticks = element_line(color = "#9C9C9C"),
                     legend.key = element_rect(fill = "#1D1E28"),
                     axis.title.x = element_text(color = "#9C9C9C"),
                     axis.title.y = element_text(color = "#9C9C9C"),
                     axis.text = element_text(color = "#9C9C9C"),
                     legend.text = element_text(color = "#9C9C9C"),
                     plot.title = element_text(color = "#9C9C9C"),
                     plot.subtitle = element_text(color = "#9C9C9C"))