blogplot_theme = theme(legend.background = element_rect(fill = "#1F222A",
                                                      color = "#1F222A"),
                     legend.title = element_blank(),
                     legend.box.background = element_rect(fill = "#1F222A",
                                                          color = "#1F222A"),
                     panel.background = element_rect(fill = "#1F222A",
                                                     color = "#1F222A"),
                     panel.grid.major = element_line(color = "#9C9C9C"),
                     panel.grid.minor = element_line(color = "#1F222A"),
                     plot.background = element_rect(fill = "#1F222A",
                                                    color = "#1F222A"),
                     axis.ticks = element_line(color = "#9C9C9C"),
                     legend.key = element_rect(fill = "#1F222A"),
                     axis.title.x = element_text(color = "#9C9C9C"),
                     axis.title.y = element_text(color = "#9C9C9C"),
                     axis.text = element_text(color = "#9C9C9C"),
                     legend.text = element_text(color = "#9C9C9C"),
                     plot.title = element_text(color = "#9C9C9C"),
                     plot.subtitle = element_text(color = "#9C9C9C"))

blogmap_theme = tm_layout(bg.color = "#1F222A",
                          frame = F,
                          legend.title.color = "#9C9C9C",
                          legend.text.color = "#9C9C9C",
                          title.color = "#9C9C9C")

