blogplot_theme = theme(legend.background = element_rect(fill = "#222129",
                                                      color = "#222129"),
                     legend.title = element_blank(),
                     legend.box.background = element_rect(fill = "#222129",
                                                          color = "#222129"),
                     panel.background = element_rect(fill = "#222129",
                                                     color = "#222129"),
                     panel.grid.major = element_line(color = "#9C9C9C"),
                     panel.grid.minor = element_line(color = "#222129"),
                     plot.background = element_rect(fill = "#222129",
                                                    color = "#222129"),
                     axis.ticks = element_line(color = "#9C9C9C"),
                     legend.key = element_rect(fill = "#222129"),
                     axis.title.x = element_text(color = "#9C9C9C"),
                     axis.title.y = element_text(color = "#9C9C9C"),
                     axis.text = element_text(color = "#9C9C9C"),
                     legend.text = element_text(color = "#9C9C9C"),
                     plot.title = element_text(color = "#9C9C9C"),
                     plot.subtitle = element_text(color = "#9C9C9C"))
ggplot()+
  blogplot_theme
